package forme;

import Writesheet.KartonExcel;
import Writesheet.KartonExcel1;
import Writesheet.KartonExcelGenerator;
import Writesheet.KartonExcelSvi;
import Writesheet.PodaciURedu;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.security.CodeSource;
import java.sql.*;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import konekcija.konekcija;
import javax.swing.*;
import maticni.MaticniPodaci;
import maticni.MaticniPodaciSaNapomenom;
import maticni.PttBrojevi;
import maticni.Ustanova;
import maticni.Zupa;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Personal extends javax.swing.JFrame {

//    public putniNalozi.putniNaloziZ putninaloziz;
    Personal parent = this;
    public Connection conn;

    public Personal() {
        
//        Prijava prijava = new Prijava();
//        prijava.setVisible(true);
        
        initComponents();
        konekcija n = new konekcija();
        conn = n.konekcija();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        DodavanjeBtn = new javax.swing.JButton();
        IzlazBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TrazenjePersoneBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PrintBtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DodavanjeBtn1 = new javax.swing.JButton();
        DodavanjeBtn2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Personal = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBanke = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuMestoSkolovanja = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuOslovljavanjeZupa = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuDekanat = new javax.swing.JMenuItem();
        jMenuArhiprezbiterat = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuDrugeUstanove = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuTipEntiteta = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidencija svećenika");

        jToolBar1.setRollover(true);

        DodavanjeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/new.png"))); // NOI18N
        DodavanjeBtn.setText("Dodaj svećenika");
        DodavanjeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodavanjeBtnActionPerformed(evt);
            }
        });

        IzlazBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/exit.png"))); // NOI18N
        IzlazBtn.setText("Izlaz");
        IzlazBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzlazBtnActionPerformed(evt);
            }
        });

        TrazenjePersoneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/filefind.png"))); // NOI18N
        TrazenjePersoneBtn.setText("Pregled svećenika");
        TrazenjePersoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrazenjePersoneBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\gui\\images\\bis600x400.jpg")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/grbbiskup-ulaz.jpg"))); // NOI18N

        PrintBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/fileprint.png"))); // NOI18N
        PrintBtn1.setText("Svećenik prikaz");
        PrintBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtn1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Verzija: 1.2");

        DodavanjeBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/new.png"))); // NOI18N
        DodavanjeBtn1.setText("Dodaj/izmeni župu");
        DodavanjeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodavanjeBtn1ActionPerformed(evt);
            }
        });

        DodavanjeBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/new.png"))); // NOI18N
        DodavanjeBtn2.setText("Dodaj/izmeni ustanovu");
        DodavanjeBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodavanjeBtn2ActionPerformed(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        Personal.setText("Svećenici");
        Personal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/group.gif"))); // NOI18N
        jMenuItem1.setText("Unos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Personal.add(jMenuItem1);

        jMenuItem17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem17.setText("Izmena");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        Personal.add(jMenuItem17);

        jMenuBar1.add(Personal);

        jMenu4.setText("Župe");
        jMenu4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem33.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem33.setText("Unos/izmena");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem33);

        jMenuItem35.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem35.setText("Pregled");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem35);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ustanove");
        jMenu5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem34.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem34.setText("Unos/izmena");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem34);

        jMenuItem36.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem36.setText("Pregled");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem36);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Matični podaci");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem7.setText("Oslovljavanje");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem8.setText("Crkvena titula");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem9.setText("Akademska titula");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem2.setText("Mjesta - rođenja/škole/bogoslovije/ređenja/župe/ustanove");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem5.setText("Nacionalnost");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBanke.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuBanke.setText("Banke");
        jMenuBanke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBankeActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuBanke);
        jMenu1.add(jSeparator1);

        jMenuItem11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem11.setText("Naziv škole - srednje obrazovanje");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuMestoSkolovanja.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuMestoSkolovanja.setText("Mjesta i naziv obrazovne ustanove dodiplomski studij/magisterij/doktorat");
        jMenuMestoSkolovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMestoSkolovanjaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuMestoSkolovanja);

        jMenuItem13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem13.setText("Zaredatelji");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);
        jMenu1.add(jSeparator3);

        jMenuOslovljavanjeZupa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuOslovljavanjeZupa.setText("Oslovljavanje župa");
        jMenuOslovljavanjeZupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOslovljavanjeZupaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuOslovljavanjeZupa);

        jMenuItem14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem14.setText("Župe");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuDekanat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuDekanat.setText("Dekanat");
        jMenuDekanat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDekanatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDekanat);

        jMenuArhiprezbiterat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuArhiprezbiterat.setText("Arhiprezbiterat");
        jMenuArhiprezbiterat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArhiprezbiteratActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuArhiprezbiterat);

        jMenuItem15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem15.setText("Svojstvo u pastoralu");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);
        jMenu1.add(jSeparator2);

        jMenuItem21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem21.setText("Ustanove");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem22.setText("Službe u ustanovi - dodatne službe");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuDrugeUstanove.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuDrugeUstanove.setText("Druge ustanove");
        jMenuDrugeUstanove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDrugeUstanoveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDrugeUstanove);
        jMenu1.add(jSeparator5);

        jMenuItem4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem4.setText("Stručna sprema");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuTipEntiteta.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuTipEntiteta.setText("Tip entiteta");
        jMenuTipEntiteta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTipEntitetaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuTipEntiteta);
        jMenu1.add(jSeparator4);

        jMenuItem3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem3.setText("Državljanstvo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem12.setText("Države");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);
        jMenu1.add(jSeparator6);

        jMenuItem10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem10.setText("Općine");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem6.setText("Svojstvo osiguranika");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Izvješća");
        jMenu2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem27.setText("Pregled službi svećenika");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem27);

        jMenuItem29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem29.setText("Pregled svećenika po župama");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem29);
        jMenu2.add(jSeparator10);

        jMenuItem16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem16.setText("Pregled svećenika");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem20.setText("Pregled po župama");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);
        jMenu2.add(jSeparator7);

        jMenuItem30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem30.setText("Koverte Župe");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem30);

        jMenuItem31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem31.setText("Koverte velike župa");
        jMenuItem31.setToolTipText("Štampa velikih koverti");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem31);

        jMenuItem32.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem32.setText("Koverte svećenici - duga");
        jMenuItem32.setToolTipText("");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem32);
        jMenu2.add(jSeparator11);

        jMenuItem23.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem23.setText("Osnovni podaci - Excel");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem26.setText("Osnovni podaci, zupa, ustanova");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem26);

        jMenuItem24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem24.setText("Karton - Excel");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem25.setText("Excel - generisani podaci");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem25);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Servis");
        jMenu3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jMenuItem18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem18.setText("Kopija podataka");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem19.setText("Restauracija podataka");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuItem28.setText("Prijave");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem28);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(255, 255, 255))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DodavanjeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrazenjePersoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(PrintBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DodavanjeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DodavanjeBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IzlazBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IzlazBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TrazenjePersoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DodavanjeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PrintBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DodavanjeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DodavanjeBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      Thread t2 = new Thread(new Runnable() {
          public void run() {
              addPersonalTab ap = new addPersonalTab(conn, "UNOS", "");
              ap.setVisible(true);
          }
      });
      t2.start();
  }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void DodavanjeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodavanjeBtnActionPerformed
        Thread t2 = new Thread(new Runnable() {
            public void run() {
                addPersonalTab ap = new addPersonalTab(conn, "UNOS","");
                ap.setVisible(true);
            }
        });
        t2.start();
    }//GEN-LAST:event_DodavanjeBtnActionPerformed

    private void IzlazBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzlazBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_IzlazBtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PttBrojevi sr = new PttBrojevi(conn, "ptt_brojevi");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MaticniPodaci sr = new MaticniPodaci(conn, "drzavljanstvo");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MaticniPodaci sr = new MaticniPodaci(conn, "strucna_sprema");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        MaticniPodaci sr = new MaticniPodaci(conn, "nacionalnost");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        MaticniPodaci sr = new MaticniPodaci(conn, "svojstvo_osiguranika");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "oslovljavanje");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "crkvena_titula");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "akademska_titula");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "opstina");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void TrazenjePersoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrazenjePersoneBtnActionPerformed
        // TODO add your handling code here:
        TrazenjePersone tp = new TrazenjePersone();
        tp.setVisible(true);
    }//GEN-LAST:event_TrazenjePersoneBtnActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "srednje_obrazovanje_skola");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "drzave");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "zaredatelj");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        Zupa sr = new Zupa(conn, "zupa");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        MaticniPodaci sr = new MaticniPodaci(conn, "svojstvo_u_sluzbi");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void PrintBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtn1ActionPerformed
        // TODO add your handling code here:
                Thread t1 = new Thread(new Runnable() {
            public void run() {
                // a jframe here isn't strictly necessary, but it makes the example a little more real
                JFrame frame = new JFrame("InputDialog ");

                // prompt the user to enter their name
                String mIzabraniId = JOptionPane.showInputDialog(frame, "Svećenikov Id?");

                try {
                    Map parameters = new HashMap();
                    parameters.put("id", mIzabraniId);
                     String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("karton1004.jrxml"); 
//                    String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\karton1004.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, parameters, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
//              Thread t1 = new Thread(new Runnable() {
//            public void run() {
//                try {
//                    String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\karton.jrxml";
//                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
//                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
//                    JasperViewer.viewReport(jp, false);
//                } catch (JRException ex) {
//                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//        t1.start();  
    }//GEN-LAST:event_PrintBtn1ActionPerformed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
                TrazenjePersone tp = new TrazenjePersone();
        tp.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
                Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("pregledPersonalaReport1.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
            Backupdbtosql();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        String s="a";
        Restoredbfromsql(s);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
                        Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("pregledPoZupama.jrxml"); 
//                    String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPoZupama.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
//                MaticniPodaci sr = new MaticniPodaci(conn, "ustanove");
                Ustanova us = new Ustanova(conn, "ustanove");
        us.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
                        MaticniPodaci sr = new MaticniPodaci(conn, "dodatne_sluzbe");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuArhiprezbiteratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArhiprezbiteratActionPerformed
        // TODO add your handling code here:
                                MaticniPodaci sr = new MaticniPodaci(conn, "arhiprezbiterat");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuArhiprezbiteratActionPerformed

    private void jMenuDekanatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDekanatActionPerformed
        // TODO add your handling code here:
                                MaticniPodaci sr = new MaticniPodaci(conn, "dekanat");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuDekanatActionPerformed

    private void jMenuOslovljavanjeZupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOslovljavanjeZupaActionPerformed
        // TODO add your handling code here:
                                MaticniPodaci sr = new MaticniPodaci(conn, "oslovljavanje_zupa");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuOslovljavanjeZupaActionPerformed

    private void jMenuDrugeUstanoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDrugeUstanoveActionPerformed
        // TODO add your handling code here:
                                MaticniPodaci sr = new MaticniPodaci(conn, "druge_ustanove");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuDrugeUstanoveActionPerformed

    private void jMenuBankeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBankeActionPerformed
        // TODO add your handling code here:
                MaticniPodaciSaNapomenom sr = new MaticniPodaciSaNapomenom(conn, "banke");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuBankeActionPerformed

    private void jMenuTipEntitetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTipEntitetaActionPerformed
        // TODO add your handling code here:
                MaticniPodaci sr = new MaticniPodaci(conn, "tip_entiteta");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuTipEntitetaActionPerformed

    private void jMenuMestoSkolovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMestoSkolovanjaActionPerformed
        // TODO add your handling code here:
                        MaticniPodaci sr = new MaticniPodaci(conn, "mesto_skolovanja");
        sr.setVisible(true);
    }//GEN-LAST:event_jMenuMestoSkolovanjaActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        KartonExcel ke = new KartonExcel();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
//        KartonExcel1 ke1 = new KartonExcel1();
        KartonExcelSvi kes = new KartonExcelSvi("");
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        KartonExcelGenerator keg = new KartonExcelGenerator();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        PodaciURedu pur = new PodaciURedu();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
                    if (Prijava.getKosam()) {
                                MaticniPodaci sr = new MaticniPodaci(conn, "reg");
        sr.setVisible(true);
            }

    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
                        Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("report4.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
                                Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("report5.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
            Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("koverteZupa1.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
            Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("koverteZupaVelika.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
                    Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("koverteSveceniciDuga.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void DodavanjeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodavanjeBtn1ActionPerformed
        // TODO add your handling code here:
                Thread t2y = new Thread(new Runnable() {
            public void run() {
                Zupa sr = new Zupa(conn, "zupa");
                sr.setVisible(true);
            }
        });
        t2y.start();
    }//GEN-LAST:event_DodavanjeBtn1ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        // TODO add your handling code here:
                Thread t2y = new Thread(new Runnable() {
            public void run() {
                Zupa sr = new Zupa(conn, "zupa");
                sr.setVisible(true);
            }
        });
        t2y.start();
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void DodavanjeBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodavanjeBtn2ActionPerformed
        // TODO add your handling code here:
                Thread t2e = new Thread(new Runnable() {
            public void run() {
                Ustanova us = new Ustanova(conn, "ustanove");
                us.setVisible(true);
            }
        });
        t2e.start();
    }//GEN-LAST:event_DodavanjeBtn2ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        // TODO add your handling code here:
                Thread t2e = new Thread(new Runnable() {
            public void run() {
                Ustanova us = new Ustanova(conn, "ustanove");
                us.setVisible(true);
            }
        });
        t2e.start();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
                                Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("pregledZupaa.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
                                        Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    String reportPath = service.uzmiParametar.uzmiParametar(conn, "putanja_izvestaja").concat("pregledUstanovaa.jrxml");
                   //  String reportPath = "C:\\Users\\ms\\Documents\\NetBeansProjects\\gui\\src\\report\\pregledPersonalaReport1.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(reportPath);
                    JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                    JasperViewer.viewReport(jp, false);
                } catch (JRException ex) {
                    Logger.getLogger(Personal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t1.start();
        
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodavanjeBtn;
    private javax.swing.JButton DodavanjeBtn1;
    private javax.swing.JButton DodavanjeBtn2;
    private javax.swing.JButton IzlazBtn;
    private javax.swing.JMenu Personal;
    private javax.swing.JButton PrintBtn1;
    private javax.swing.JButton TrazenjePersoneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuArhiprezbiterat;
    private javax.swing.JMenuItem jMenuBanke;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDekanat;
    private javax.swing.JMenuItem jMenuDrugeUstanove;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuMestoSkolovanja;
    private javax.swing.JMenuItem jMenuOslovljavanjeZupa;
    private javax.swing.JMenuItem jMenuTipEntiteta;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void Backupdbtosql() {
            try {

        /*NOTE: Getting path to the Jar file being executed*/
        /*NOTE: YourImplementingClass-> replace with the class executing the code*/
        CodeSource codeSource = Personal.class.getProtectionDomain().getCodeSource();
        File jarFile = new File(codeSource.getLocation().toURI().getPath());
        String jarDir = jarFile.getParentFile().getPath();


        /*NOTE: Creating Database Constraints*/
        String dbName = "personal";
        String dbUser = "porta";
        String dbPass = "porta1";

        /*NOTE: Creating Path Constraints for folder saving*/
        /*NOTE: Here the backup folder is created for saving inside it*/
        String folderPath = jarDir + "\\backup";

        /*NOTE: Creating Folder if it does not exist*/
        File f1 = new File(folderPath);
        f1.mkdir();

        
        java.util.Date currentDate = GregorianCalendar.getInstance().getTime();
        Format formatter = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");
        String s = formatter.format(currentDate);


        /*NOTE: Creating Path Constraints for backup saving*/
        /*NOTE: Here the backup is saved in a folder called backup with the name backup.sql*/
         String savePath = "\"" + jarDir + "\\backup\\" + "backup-" + s + ".sql\"";

        /*NOTE: Used to create a cmd command*/
//        String executeCmd = "c:\\wamp\\bin\\mysql\\mysql5.6.12\\bin\\mysqldump -u" + dbUser + " -p" + dbPass + " --database " + dbName + " -r " + savePath;
        String executeCmd = "c:\\xampp\\mysql\\bin\\mysqldump -u" + dbUser + " -p" + dbPass + " --database " + dbName + " -r " + savePath;

        /*NOTE: Executing the command here*/
        Process runtimeProcess = Runtime.getRuntime().exec(executeCmd);
        int processComplete = runtimeProcess.waitFor();

        /*NOTE: processComplete=0 if correctly executed, will contain other values if not*/
        if (processComplete == 0) {
            System.out.println("Backup Complete");
            JOptionPane.showMessageDialog(null, "Successfully backup : " + savePath);
        } else {
            System.out.println("Backup Failure");
        }

    } catch (URISyntaxException | IOException | InterruptedException ex) {
        JOptionPane.showMessageDialog(null, "Error at Backuprestore" + ex.getMessage());
    }
    }

    private void Restoredbfromsql(String s) {
       try {
            /*NOTE: String s is the mysql file name including the .sql in its name*/
            /*NOTE: Getting path to the Jar file being executed*/
            /*NOTE: YourImplementingClass-> replace with the class executing the code*/
            CodeSource codeSource = Personal.class.getProtectionDomain().getCodeSource();
            File jarFile = new File(codeSource.getLocation().toURI().getPath());
            String jarDir = jarFile.getParentFile().getPath();

            /*NOTE: Creating Database Constraints*/
             String dbName = "YourDBName";
             String dbUser = "YourUserName";
             String dbPass = "YourUserPassword";

            /*NOTE: Creating Path Constraints for restoring*/
            String restorePath = jarDir + "\\backup" + "\\" + s;

            /*NOTE: Used to create a cmd command*/
            /*NOTE: Do not create a single large string, this will cause buffer locking, use string array*/
            String[] executeCmd = new String[]{"mysql", dbName, "-u" + dbUser, "-p" + dbPass, "-e", " source " + restorePath};

            /*NOTE: processComplete=0 if correctly executed, will contain other values if not*/
            Process runtimeProcess = Runtime.getRuntime().exec(executeCmd);
            int processComplete = runtimeProcess.waitFor();

            /*NOTE: processComplete=0 if correctly executed, will contain other values if not*/
            if (processComplete == 0) {
                JOptionPane.showMessageDialog(null, "Successfully restored from SQL : " + s);
            } else {
                JOptionPane.showMessageDialog(null, "Error at restoring");
            }


        } catch (URISyntaxException | IOException | InterruptedException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error at Restoredbfromsql" + ex.getMessage());
        }

    }
    
}
